from django.core.management.base import BaseCommand
from cadastro.models import TechnologyCategory


class Command(BaseCommand):
    help = 'Popula a tabela TechnologyCategory com uma lista de categorias de tecnologia'

    def handle(self, *args, **kwargs):
        categories = [
            {"name": "Logística Reversa",
             "description": "Tecnologias para o reaproveitamento e reciclagem de produtos."},
            {"name": "Agricultura de Precisão",
             "description": "Uso de sensores e dados para otimizar a produção agrícola."},
            {"name": "Reconhecimento de Padrões",
             "description": "Sistemas que identificam padrões em grandes volumes de dados."},
            {"name": "Tecnologia de Refrigeração",
             "description": "Inovações para sistemas de refrigeração mais eficientes."},
            {"name": "Monitoramento Ambiental",
             "description": "Sistemas para monitoramento e preservação de ecossistemas."},
            {"name": "Economia Circular",
             "description": "Tecnologias para maximizar o uso de recursos e reduzir desperdícios."},
            {"name": "Bioplásticos",
             "description": "Desenvolvimento de plásticos biodegradáveis feitos a partir de recursos renováveis."},
            {"name": "Tecnologia de Irrigação",
             "description": "Soluções tecnológicas para otimizar o uso da água na agricultura."},
            {"name": "Tecnologia Assistiva para Mobilidade",
             "description": "Inovações que ajudam pessoas com deficiências a se locomoverem."},
            {"name": "Smart Contracts", "description": "Contratos automatizados e autoexecutáveis em blockchain."},
            {"name": "Realidade Holográfica", "description": "Projeções holográficas interativas em ambientes reais."},
            {"name": "Inteligência Coletiva",
             "description": "Tecnologias que permitem a colaboração em massa para resolver problemas."},
            {"name": "Construção Modular", "description": "Métodos construtivos utilizando módulos pré-fabricados."},
            {"name": "Governança Digital",
             "description": "Soluções tecnológicas para gestão pública digital e transparência."},
            {"name": "Tecnologia de Produção Alimentar",
             "description": "Inovações que aumentam a eficiência na produção de alimentos."},
            {"name": "Sensores Biométricos",
             "description": "Dispositivos que identificam pessoas por características físicas ou comportamentais."},
            {"name": "Energia Solar Flutuante",
             "description": "Painéis solares instalados em corpos d'água para geração de energia."},
            {"name": "Sistemas Autônomos",
             "description": "Tecnologias que permitem a automação completa de processos."},
            {"name": "Tecnologia de Armazenamento de Energia",
             "description": "Inovações para armazenar energia de maneira mais eficiente."},
            {"name": "Plataformas de Streaming",
             "description": "Soluções para transmissão de conteúdos ao vivo ou sob demanda."},
            {"name": "Gestão Inteligente de Tráfego",
             "description": "Sistemas que otimizam a fluidez do tráfego urbano."},
            {"name": "Tecnologia de Prevenção de Desastres",
             "description": "Soluções que detectam e previnem desastres naturais ou industriais."},
            {"name": "Tecnologias Inclusivas", "description": "Soluções que promovem inclusão social e digital."},
            {"name": "Tecnologia de Empacotamento Inteligente",
             "description": "Embalagens que monitoram e informam sobre a condição do produto."},
            {"name": "Tecnologia de Tratamento de Água",
             "description": "Inovações no tratamento e purificação de água."},
            {"name": "Engenharia de Materiais Avançados",
             "description": "Desenvolvimento de novos materiais com propriedades inovadoras."},
            {"name": "Telerobótica", "description": "Controle de robôs à distância por meio de redes de comunicação."},
            {"name": "Sistemas de Análise Preditiva",
             "description": "Tecnologias que usam dados históricos para prever tendências futuras."},
            {"name": "Economia Digital",
             "description": "Uso de tecnologias para criar novos modelos de negócios digitais."},
            {"name": "Marketing Digital",
             "description": "Estratégias tecnológicas para promoção de produtos e serviços online."},
            {"name": "Plataformas de Aprendizado Online",
             "description": "Ambientes digitais para ensino e aprendizado."},
            {"name": "Computação Verde",
             "description": "Desenvolvimento de tecnologias de baixo impacto ambiental para computação."},
            {"name": "Fabricação Inteligente",
             "description": "Uso de tecnologias digitais para melhorar a produção industrial."},
            {"name": "Segurança Digital em IoT",
             "description": "Soluções de segurança para dispositivos conectados na Internet das Coisas."},
            {"name": "Tecnologia de Impressão Eletrônica",
             "description": "Inovações para impressão de circuitos e componentes eletrônicos."},
            {"name": "Análise de Redes Sociais",
             "description": "Sistemas que analisam interações e dados de redes sociais."},
            {"name": "Tecnologia de Automação Comercial",
             "description": "Soluções para otimização de operações comerciais."},
            {"name": "Tecnologia de Eficiência Energética",
             "description": "Inovações para redução do consumo de energia."},
            {"name": "Gestão Inteligente de Processos",
             "description": "Automação e controle de processos empresariais com base em dados."},
            {"name": "Ciência Computacional",
             "description": "Estudo e aplicação de métodos computacionais para resolver problemas complexos."},
            {"name": "Técnicas de Detecção de Fraude",
             "description": "Soluções que detectam atividades fraudulentas em sistemas digitais."},
            {"name": "Pagamentos por Aproximação",
             "description": "Tecnologia que permite pagamentos sem contato físico."},
            {"name": "Hiperautomação",
             "description": "Uso de IA, robótica e automação para potencializar processos em larga escala."},
            {"name": "Tecnologia para Mobilidade Elétrica",
             "description": "Inovações para veículos elétricos e infraestrutura de carregamento."},
            {"name": "Ferramentas de Análise de SEO",
             "description": "Soluções para otimização de mecanismos de busca."},
            {"name": "Armazenamento em Nuvem Híbrida",
             "description": "Combinação de soluções de nuvem privada e pública para armazenar dados."},
            {"name": "Tecnologia de Interface Neural",
             "description": "Inovações que permitem a interação entre o cérebro humano e máquinas."},
            {"name": "Sistemas de Produção Inteligente",
             "description": "Tecnologias para automatizar e otimizar a fabricação de produtos."},
            {"name": "Tecnologia para Diagnóstico por Imagem",
             "description": "Inovações em equipamentos e técnicas para diagnóstico por imagem."},
            {"name": "Assistentes Pessoais Virtuais",
             "description": "Sistemas que auxiliam usuários em suas tarefas diárias através da IA."},
            {"name": "Robótica Cirúrgica",
             "description": "Sistemas robóticos para assistência em cirurgias minimamente invasivas."},
            {"name": "Imunoterapia",
             "description": "Tecnologias para o tratamento de doenças utilizando o sistema imunológico."},
            {"name": "Tecnologia de Nanomedicina",
             "description": "Aplicações da nanotecnologia na medicina para tratamento de doenças."},
            {"name": "Tecnologia de Higienização Automática",
             "description": "Soluções para higienização e esterilização automatizadas."},
            {"name": "Monitoramento em Tempo Real",
             "description": "Sistemas para coleta e análise de dados em tempo real."},
            {"name": "Educação Adaptativa",
             "description": "Sistemas de ensino que se ajustam às necessidades de aprendizado dos alunos."},
            {"name": "Plataformas de Microfinanças",
             "description": "Tecnologias que facilitam empréstimos e serviços financeiros de pequeno porte."},
            {"name": "Mapeamento Genético",
             "description": "Soluções para o sequenciamento e análise do genoma humano."},
            {"name": "Redes de Sensores sem Fio",
             "description": "Tecnologias que conectam sensores através de redes sem fio para monitoramento remoto."},
            {"name": "Tecnologia para Biometria Ocular",
             "description": "Inovações para identificação e autenticação por meio de características oculares."},
            {"name": "Rastreamento por RFID",
             "description": "Tecnologia de identificação por radiofrequência para rastreamento de objetos."},
            {"name": "Segurança de Infraestrutura Crítica",
             "description": "Soluções para proteger infraestruturas essenciais como energia e transportes."},
            {"name": "Tecnologias de Micromanufatura",
             "description": "Sistemas para produção de componentes em escalas extremamente pequenas."},
            {"name": "Tecnologia de Simulação em VR",
             "description": "Ambientes virtuais para simulação de cenários complexos."},
            {"name": "Blockchain para Cadeia de Suprimentos",
             "description": "Uso de blockchain para rastrear e garantir a integridade de cadeias de suprimentos."},
            {"name": "Tecnologia de Produção de Alimentos Sintéticos",
             "description": "Inovações para produção de alimentos artificiais, como carne cultivada em laboratório."},
            {"name": "Redes Privadas Virtuais",
             "description": "Soluções para criação de redes privadas seguras através da internet."},
            {"name": "Tecnologias de Sequenciamento de DNA",
             "description": "Soluções para análise e compreensão do DNA de forma mais rápida e acessível."},
            {"name": "Tecnologia para Recuperação de Dados",
             "description": "Soluções para recuperação de informações perdidas ou corrompidas."},
            {"name": "Microsserviços",
             "description": "Arquitetura de software que divide grandes aplicações em pequenos serviços independentes."},
            {"name": "Sistemas de Otimização de Estoques",
             "description": "Tecnologias para gerenciamento e otimização de inventários."},
            {"name": "Tecnologia de Análise de Sentimento",
             "description": "Ferramentas que analisam o humor ou a opinião em dados textuais."},
            {"name": "Tecnologia para Agricultura Vertical",
             "description": "Inovações para cultivar plantas em camadas empilhadas em ambientes controlados."},
            {"name": "Tecnologia de Drones para Entregas",
             "description": "Sistemas de drones para entregas rápidas e eficientes."},
            {"name": "Assistência Remota Médica",
             "description": "Soluções para telemedicina e consultas médicas à distância."},
            {"name": "Sistemas de Rastreamento de Carbono",
             "description": "Tecnologias para monitoramento e redução de emissões de carbono."},
            {"name": "Tecnologia de Geração Eólica Offshore",
             "description": "Soluções para geração de energia eólica em alto-mar."},
            {"name": "Plataformas de Gestão Colaborativa",
             "description": "Ferramentas que facilitam a colaboração em projetos empresariais e acadêmicos."},
            {"name": "Sistemas de Feedback de Usuários",
             "description": "Tecnologias para coleta e análise de feedback de consumidores."},
            {"name": "Tecnologia de Controle de Pragas",
             "description": "Inovações no controle de pragas agrícolas e urbanas."},
            {"name": "Modelagem Predictiva",
             "description": "Soluções que utilizam dados históricos para prever eventos futuros."},
            {"name": "Tecnologia de Bioconstrução",
             "description": "Uso de materiais e técnicas sustentáveis na construção civil."},
            {"name": "Automação de Processos Industriais",
             "description": "Tecnologias que otimizam e automatizam processos em fábricas."},
            {"name": "Inteligência de Mercado",
             "description": "Ferramentas para análise de tendências e comportamentos de mercado."},
            {"name": "Tecnologia de Monitoramento de Saúde",
             "description": "Soluções para monitorar sinais vitais e dados médicos em tempo real."},
            {"name": "Proteção de Dados Pessoais",
             "description": "Soluções que garantem a segurança e privacidade de dados de indivíduos."},
            {"name": "Tecnologias Híbridas de Nuvem",
             "description": "Combinação de serviços de nuvem pública e privada para maior flexibilidade e segurança."},
            {"name": "Tecnologia de Fabricação Aditiva",
             "description": "Soluções para a produção de objetos em camadas, como impressão 3D."},
            {"name": "Sensores Químicos",
             "description": "Dispositivos que detectam e medem a presença de substâncias químicas."},
            {"name": "Outros",
             "description": "Não encontrei algo que represente meu projeto"}
        ]

        for category in categories:
            TechnologyCategory.objects.get_or_create(
                name=category["name"],
                defaults={"description": category["description"]},
            )

        self.stdout.write(self.style.SUCCESS('50 categorias populadas com sucesso!'))
