# Generated by Django 4.1.3 on 2024-10-05 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_alter_feedback_id_alter_impactreport_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nome',
            field=models.CharField(default=2, max_length=300),
            preserve_default=False,
        ),
    ]
