# Generated by Django 4.1.3 on 2024-10-06 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_regiao_estado_cidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='location_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.cidade'),
        ),
        migrations.AddField(
            model_name='project',
            name='location_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.estado'),
        ),
        migrations.AddField(
            model_name='project',
            name='needs',
            field=models.ManyToManyField(blank=True, related_name='projects', to='cadastro.need'),
        ),
    ]
