# Generated by Django 4.1.3 on 2024-10-06 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_need_project_keywords_project_location_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorshiprequest',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_offers', to='cadastro.userprofile'),
        ),
    ]
