# Generated by Django 4.1.3 on 2024-10-06 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_alter_mentorshiprequest_mentor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorshiprequest',
            name='mentor',
        ),
        migrations.CreateModel(
            name='MentorInterested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_requests', to='cadastro.userprofile')),
                ('mentorship_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_mentors', to='cadastro.mentorshiprequest')),
            ],
        ),
    ]
