# Generated by Django 4.1.3 on 2024-10-07 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_remove_mentorshiprequest_mentor_mentorinterested'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnershiprequest',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='partnershiprequest',
            name='partner_email',
        ),
        migrations.RemoveField(
            model_name='partnershiprequest',
            name='partner_name',
        ),
        migrations.RemoveField(
            model_name='partnershiprequest',
            name='requester',
        ),
        migrations.RemoveField(
            model_name='partnershiprequest',
            name='status',
        ),
        migrations.AddField(
            model_name='partnershiprequest',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='partnershiprequest',
            name='message',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='PartnerInterested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnership_requests_made', to='cadastro.userprofile')),
                ('partnership_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_partners', to='cadastro.partnershiprequest')),
            ],
        ),
    ]
