# Generated by Django 4.1.3 on 2024-10-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0012_partnerinterested_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='projetos_logos/'),
        ),
    ]
